/////////////////////////////////////////////////////////////////
//
// Copyright (C) 2005 Affymetrix, Inc.
//
// This library is free software; you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published
// by the Free Software Foundation; either version 2.1 of the License,
// or (at your option) any later version.
//
// This library is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
// or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License
// for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this library; if not, write to the Free Software Foundation, Inc.,
// 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA 
//
/////////////////////////////////////////////////////////////////

package affymetrix.calvin.utils;

import java.io.UnsupportedEncodingException;
import java.util.UUID;
import java.util.Arrays;

/** Provides a type for the Affy GUID.  
 *  
 *  Affymetrix software requires GUIDs to be unique.  
 *  In order to provide maximum flexibility for users our software, 
 *  Affymetrix does not require GUIDs to be RFC 4122 compliant.
 *  
 *  The GUIDs generated by the generateGuid function in the 
 *  Java SDJ are RFC 4122 compliant.  * 
 * */
public class AffymetrixGuidType {

	public static final Object GUID_LENGTH = null;


	/** The guid. */
	private byte[] guid;

	/** Creates a new instance of AffymetrixGuidType */
	public AffymetrixGuidType() {
		guid = new byte[0];
		clear();
	}
	
	
	public AffymetrixGuidType(boolean generateGuid) {
		this();
		if(generateGuid){
			generateGuid();
		}
	}

	public AffymetrixGuidType(String g) {
		this();
		setGuid(g);
	}

	public AffymetrixGuidType(byte[] g) {
		this();
		setGuid(g);
	}

	/** Gets the guid. */
	public byte[] getGuid() {
		return guid;
	}

	/**
	 * Sets the guid.
	 * 
	 * @param g
	 *          The guid.
	 */
	public void setGuid(byte[] g) {
		guid = new byte[g.length];
		System.arraycopy(g, 0, guid, 0, g.length);		
	}

	public void setGuid(String g) {
		try {
			setGuid(g.getBytes("US-ASCII"));
		}
		catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
	}

	public void setGuid(AffymetrixGuidType g) {
		guid = g.getGuid();
	}

	public void clear() {
		for (int i = 0; i < guid.length; i++) {
			guid[i] = 0;
		}
	}

	public boolean isEmpty() {
		if (guid.length == 0)
			return true;
		for (int i = 0; i < guid.length; i++) {
			if (guid[i] != 0) {
				return false;
			}
		}
		return true;
	}

	public boolean equals(AffymetrixGuidType g) {
		return Arrays.equals(guid, g.getGuid());
	}

	public void generateGuid() {
		String s = UUID.randomUUID().toString(); 			
		setGuid(s);		
	}

	@Override
	public String toString() {
		try {
			int end=0;	//trim off the zero bytes
			for(; end<guid.length; ++end) {	//look for the first zero byte until we reach the end of the byte array
				if(guid[end]==0) {	//if this is a zero byte, we'll trim to here
					break;	//stop looking for the first zero byte
				}
			}
			return new String(guid, 0, end, IOUtils.ASCII_CHARSET);	//create a string from the beginning up to the first zero byte (or the end, if there are no zero bytes)
		}
		catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		}
		return null;
	}
}
